### ISSUE TITLE
Logging non-shared resident memory

### ISSUE THREAD

**Issue by progval** [vigna/dsi-progress-logger-rs#6]
ProgressLogger prints the current resident memory (as "used").

However, because of how often we use it while working with large memory-mapped files, this is not very useful, as it includes the shared memory (ie. the parts of the mmaped files that are cached in memory).

**Comment by vigna** [comment]
It's worse—on MacOS it does not include that amount. It's entirely system-dependent. That's why I link the `sysinfo` doc.

**Comment by vigna** [comment]
The strategy is: I'm giving you anything `sysinfo` will give you. Platform-wise... figure it out 🤷🏻‍♂️.
